# -*- coding: utf-8 -*-
"""Lab2_CSE420.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnnq1pxrV0r6KcZRoCM6ahv0l6h0TIQs
"""

f = open("input1.txt","r").read().split("\n")
print(f)

def web(t):
  alphabet=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',"A","B","C","D","E",'F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
  number=[1,2,3,4,5,6,7,8,9,0]
  temp=t.split(".")

  if temp[0] =='www':#check if "www" is present
    after=t[4:]
    for i in range(len(after)):
      if "." not in after:
        return "invalid"
      elif after[i]==".":# check after ".", there are alphabets and numbers+ no consecutive dots
        if (after[i+1] in number or after[i+1] in alphabet) and i!=0:
          continue
        else:
          return "invalid"
      elif after[i] in number or after[i] in alphabet: # allow alphabets and numbers
        continue
      else:
        return "invalid"
    tem=temp[-1]#check after last "." all alphabets
    for i in tem:
      if i not in alphabet:
        return "invalid"
      else:
        continue
    return "web"
  else:
    return "invalid"

def email(t):
  alphabet=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',"A","B","C","D","E",'F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
  number=[1,2,3,4,5,6,7,8,9,0]
  sc_l=["#", "!" ,"%", "$", "‘", "&", "+", "*","–", "/", "=", "?", "^", "_","`",".", "{" ,"|", "}", "~"]
  sc_d=[".","-"]

  if "@" not in t:# check if @ is present in email
    return "invalid"
  temp=t.split("@")
  local=temp[0]
  domain=temp[1]

  if local==" " or domain==" ":# check if before and after of @ is empty
    return "invalid"
  if "." not in domain:# check if "." is in both parts
    return "invalid"
  if local[0] not in alphabet:
    return "invalid"


  #check the local part
  for i in range(1,len(local)):
    if local[i] in alphabet or local[i] in number: # allow other letters alphabet and number
      continue
    elif local[i] in sc_l:# check if special character are given double, one after another
      special_char=local[i]
      if local[i+1]!=special_char or (local[i+1] in alphabet or local[i+1] in number):# allow alphabets and numbers after special charecter
        continue
      else:
        return "invalid"
    else:
      return "invalid"

  #check the domain part
  for i in range(len(domain)):
    if (i==0 or i==(len(domain)-1)) and (domain[i]!= "-" or domain[i]!= "."):#check if after @, is there any "." in last and 1st position
      continue
    elif domain[i]== "-" or domain[i]== ".":# after ./-, there should be alphabet
      again=domain[i]
      if (domain[i+1] in alphabet and domain[i+1] not in sc_d):
        continue
      else:
        return "invalid"
    elif domain[i] in alphabet or domain[i] in number:#allow alphabets and numbers
      continue
    else:
      return "invalid"
  return "email"

n=int(f[0])
for i in range(n):
  task=f[i+1]
  if web(task)=="web":
    print("Web,",i+1)
  elif email(task)=="email":
    print("Email,",i+1)
  else:
    print("Invalid,",i+1)